-- AlterTable
ALTER TABLE "public"."Project" ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "isPinned" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "pinnedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "timeStatus" DOUBLE PRECISION NOT NULL DEFAULT 0.00;

-- AlterTable
ALTER TABLE "public"."Task" ADD COLUMN     "timeStatus" DOUBLE PRECISION NOT NULL DEFAULT 0.00;
